export default {
  // lockSolid: require('assets/images/lock-solid.png'),
  profileIcon: require('assets/images/profile.png'),
  facebook: require('assets/images/facebook.png'),
  google: require('assets/images/google.png'),
  guard: require('assets/images/guard.png'),
  employee: require('assets/images/employee.png'),
  yellow: require('assets/images/yellow.png'),
  lock: require('assets/images/lock.png'),
  headerBack: require('assets/images/headerBack.png'),
  userPic: require('assets/images/user-pic.png'),
  pencil: require('assets/images/pencil.png'),
  home: require('assets/images/home.png'),
  calendar: require('assets/images/calendar.png'),
  clock: require('assets/images/clock.png'),
  profileTabIcon: require('assets/images/profile-icon.png'),
  contactUsTabIcon: require('assets/images/contactUsTabIcon.png'),
  notesTabIcon: require('assets/images/notesTabIcon.png'),
  profileEdit: require('assets/images/profile-edit.png'),
};
